### ISSUE TITLE
Add a guide for using this provider

### ISSUE THREAD

**Issue by prologic** [aucloud/terraform-provider-swarm#2]
See [Guides](https://www.terraform.io/docs/registry/providers/docs.html#guides)

**Comment by prologic** [comment]
cc @alexperezau I _think_ you should write some guides here as a user of this Provider. I _think_ it best I take a bit of a backseat here in an effort to get unbiased doco and guides(_as I wrote most of the code_). Mind giving this a crack? 🤔

**Comment by alexperezau** [comment]
> cc @alexperezau I _think_ you should write some guides here as a user of this Provider. I _think_ it best I take a bit of a backseat here in an effort to get unbiased doco and guides(_as I wrote most of the code_). Mind giving this a crack? 🤔

On it mate. Makes sense to me.

**Comment by alexperezau** [comment]
https://github.com/aucloud/terraform-provider-swarm/pull/3
